### ISSUE TITLE
Discussion: Observations so far on Pull 16e78cf

### ISSUE THREAD

**Issue by GhostlyCrowd** [CAP1Sup/Intellistep#1]
So it doesn't scream, calibration doesn't really make meaningful movements a few steps are done and after about 90 seconds it says its finished, its definitely not making several dozen steps in each direction.

As you have already seen, no stepper movement in closed loop when I send g code commands.  In open loop a movement command ever so slightly jiggles the stepper drive shaft. Like you have to be holding it to detect it., but not always, 80% of the time it does not react at all to movement g code. 

Just wanted to get a thread started

**Comment by CAP1Sup** [comment]
Yup, I'm currently working on this. I believe that the phase multiplier and stepping angle are set incorrectly, causing the coils to be incorrectly driven, causing the noise and lack of /unsmooth movement. I'm currently working on this. Thanks for the heads up, I like seeing these issues.
