### ISSUE TITLE
Incorrect saving of the configuration to memory

### ISSUE THREAD

**Issue by svsergo** [CAP1Sup/Intellistep#107]
The writeFlash function is described under the same name several times.  After saving the configuration, it is read incorrectly.

**Comment by CAP1Sup** [comment]
Could you explain what you mean further? The writeFlash function is overloaded, allowing it to execute different code based on the data type that is being stored. The readFlash functions could not be overloaded because C++ doesn't support overloading based on return types, leading to the renaming of the readFlash functions so that they have the data type at the end (ex readFlashU32).

**Comment by svsergo** [comment]
This is an assumption that the error may be in this. After saving the configuration in flash, the information is no longer displayed on the screen. It is displayed again only after the Wipe operation.  
![BTTS42Bv2](https://user-images.githubusercontent.com/52426708/131868674-a58e40bb-5d7d-4e09-8721-963bf4742d84.jpg)

**Comment by CAP1Sup** [comment]
Hmm... I'll take a look into it.

**Comment by CAP1Sup** [comment]
@svsergo are you on the master or dev branch? (Default is master)

**Comment by svsergo** [comment]
The firmware is loaded from the branch dev.

**Comment by svsergo** [comment]
I checked the firmware from the master branch. The error is repeated.

**Comment by CAP1Sup** [comment]
Excellent, that gives me a good idea of where I need to look. I haven't been able to test the recent updates as I've been busy and need the motors working at 100%, so I figured something like this would eventually happen. I'll get on it and hopefully have it solved by next week

**Comment by CAP1Sup** [comment]
Alright, it was a quick fix! I somehow forgot to write the encoder offset when saving the parameters. The board went to load it, but was unable to, causing the "nan" issue. It should be fixed now. Let me know how it goes

**Comment by svsergo** [comment]
Ok. Saving to memory works correctly.

**Comment by svsergo** [comment]
An additional problem appeared during testing.  
![ERR](https://user-images.githubusercontent.com/52426708/132033488-f8ff1657-8691-47b3-beaf-db646389dcd6.jpg)
