### ISSUE TITLE
Legacy code

### ISSUE THREAD

**Issue by IhorNehrutsa** [CAP1Sup/Intellistep#33]
I see that 
https://github.com/CAP1Sup/Intellistep/tree/master/legacy
copied from the
https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/tree/master/S42B/firmware/S42BV1.0
but, not from the 
https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/tree/master/S42B/firmware/S42BV2.0
with the CAN

**Comment by CAP1Sup** [comment]
My bad, I can't believe that I mixed them up. I have replaced the files in 394922e80e14bb53c551d67138e696f284329689.
