### ISSUE TITLE
A4950 PWM frequency

### ISSUE THREAD

**Issue by IhorNehrutsa** [CAP1Sup/Intellistep#39]
There is no maximum PWM frequency in the A4950 datasheet.
![image](https://user-images.githubusercontent.com/70886343/123779156-8a518300-d8da-11eb-9625-421e1241d78b.png)
1/34us == 29.5kHz 

It seems 30kHz is the limit of PWM.

**Comment by CAP1Sup** [comment]
All done

**Comment by IhorNehrutsa** [comment]
The above assumptions are incorrect!

140kHz measured in origin BTT board.

![image](https://user-images.githubusercontent.com/70886343/124882345-f3bb4b00-dfd8-11eb-8f3a-46b415313454.png)
R10-C8 and R7C11 are integration circuits. 
Chain MotordriverU4#PWM is a U4 Uref voltage.
