### ISSUE TITLE
If disable CAN then encoder is blocked

### ISSUE THREAD

**Issue by IhorNehrutsa** [CAP1Sup/Intellistep#77]
To reproduce the error, comment out the line 
https://github.com/CAP1Sup/Intellistep/blob/a8546f44709449c86ac5067fbde60f9c229bf54a/src/user/config.h#L62

It seems is bug here 
https://github.com/CAP1Sup/Intellistep/blob/a8546f44709449c86ac5067fbde60f9c229bf54a/src/lib/eXoCAN/eXoCAN.cpp#L95-L105

**Comment by CAP1Sup** [comment]
Please confirm that this is fixed, then I will close the issue

**Comment by CAP1Sup** [comment]
@IhorNehrutsa is this fixed? I haven't had a chance to test it myself.

**Comment by IhorNehrutsa** [comment]
Yes, it works

**Comment by CAP1Sup** [comment]
I was doing some testing and disabled the CAN functionality. I was unable to get the encoder to send values. I re-enabled CAN and everything was good. No idea what changed, but this needs to be looked into again.
