### ISSUE TITLE
StepperMotor::currentAngle is only calculated, but never used

### ISSUE THREAD

**Issue by IhorNehrutsa** [CAP1Sup/Intellistep#80]
![image](https://user-images.githubusercontent.com/70886343/126748164-aec5ab83-3fc1-4287-9d96-af9fa8c14495.png)
Also possible a method
```
float StepperMotor::getCurrentAngle() {
    return microstepAngle * currentStep;
}
```

**Comment by IhorNehrutsa** [comment]
I propose to remove StepperMotor::currentAngle completely.

**Comment by CAP1Sup** [comment]
You're right, there's no need. Commit eb0eea3e99c89f368be3881650b53015eace8313 removes it
