### ISSUE TITLE
StepperMotor::desiredAngle is only calculated, but never used

### ISSUE THREAD

**Issue by IhorNehrutsa** [CAP1Sup/Intellistep#81]
![image](https://user-images.githubusercontent.com/70886343/126749878-312b69c3-e7d7-48c5-9751-5defae357016.png)

**Comment by IhorNehrutsa** [comment]
I propose to remove it completely.

**Comment by CAP1Sup** [comment]
The desiredAngle is only there if the option to use a hardware counter is disabled. I want to ensure that we don't have any issues with the current configuration before removing the original counting method. Basically, it's not included if `USE_HARDWARE_STEP_CNT` is enabled, so the performance isn't affected.

**Comment by CAP1Sup** [comment]
You know what, this is dumb. I removed it on eb0eea3e99c89f368be3881650b53015eace8313
