### ISSUE TITLE
COUNTER_CLOCKWISE

### ISSUE THREAD

**Issue by IhorNehrutsa** [CAP1Sup/Intellistep#85]
Why COUNTER_CLOCKWISE is a positive direction?
https://github.com/CAP1Sup/Intellistep/blob/e26edef4768ef7cf92c193eff6bdf867d0400dce/src/hardware/motor.cpp#L523-L530

**Comment by CAP1Sup** [comment]
Because in physics, CCW is usually the positive direction. I didn't think it would matter, so I picked the one that made sense with the physics that I knew

**Comment by IhorNehrutsa** [comment]
https://www.api.simply.science/index.php/math/geometry/lines-and-angles/angles/1472-positive-and-negative-angles
